remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
title: dumber
aux_links:
  dumber:
    - "//github.com/dumberjs/dumber"
  gulp-dumber:
    - "//github.com/dumberjs/gulp-dumber"
  dumber-module-loader:
    - "//github.com/dumberjs/dumber-module-loader"
