remote_theme: pmarsceill/just-the-docs
url: //dumber.js.org
search_enabled: true
# color_scheme: wider
title: dumber
aux_links:
  dumber:
    - "//github.com/dumberjs/dumber"
  gulp-dumber:
    - "//github.com/dumberjs/gulp-dumber"
  dumber-module-loader:
    - "//github.com/dumberjs/dumber-module-loader"
